### ISSUE TITLE
Only System Databases appear in Select Database dropdown

### ISSUE THREAD

**Issue by bohnetn** [gitsql/SQL-Server-Edition#11]
I just sent this to your support email, but it bounced back :(

I have a SQLEXPRESS 2012 install (ver. 11.5058) on my local machine that I can connect to with the gitSQL tool, but am only able to see the System databases on the second screen, ‘Select Database’.
I am unable to see the local databases that I have created to put into your source control tool.  Using Windows Authentication.

**Sorry, figured it out... removed SQLEXPRESS in the Instance name field as it as DB is on same machine as giSQL.

**Comment by bohnetn** [comment]
Closed

**Comment by anupsaund** [comment]
Hi Bohnetn,

Thanks for getting in touch via github.

We are sorry about the support email glitch. 

We changed our email MX entry and it took some time to propagate. Feel free to drop us any new queries to the support email.

This ticket was worthwhile for us because it triggered a new test machine build of SQL Server 2012 Express SP2.

Thanks again for logging the query.

**Comment by bohnetn** [comment]
Thanks for getting back to me.

I closed the issue.  My oversight - read your instructions again and
realized I had to leave the Instance field blank if SQL Express is on the
same local machine.

So far so good otherwise. ..

Nick
