### ISSUE TITLE
Download - malicious website blocked

### ISSUE THREAD

**Issue by joshmorel** [gitsql/SQL-Server-Edition#22]
Hello,

I got this warning from Trend Microscan when trying to download SQL Server edition.

http://gitsql.net/content/getfile.php?Down=1
Rating:	Dangerous.	Verified fraud page or threat source.
What You Can Do:
Contact your administrator about security settings on your network

Josh

**Comment by mariascott** [comment]
Hi Josh,

Sorry to hear that the download was blocked.
We had a look at the trend micro website to see why it was being blocked.

https://global.sitesafety.trendmicro.com/result.php

It looks like download was being blocked because our website runs as secure https but the download link was unsecured, http.

We have changed the download link to be secured.

Please have another go at downloading the SQL Server Edition.

Let us know how you get on.

**Comment by joshmorel** [comment]
Works now thanks!

You'll need to change the GitHub README download links as well.

**Comment by mariascott** [comment]
Thank you.

Readme updated.
