### ISSUE TITLE
Importing into Existing Database SQL Server 2014

### ISSUE THREAD

**Issue by douglas-hirsh** [gitsql/SQL-Server-Edition#6]
I am having a problem getting import to work. I am using the localdb v12.0.2000 (SQL Server 2014) that comes with VS 2015. Export works just fine.
I exported 4 tables and 4 procedures. Then I created a new database and went through the steps for importing. And nothing showed up but I didn't get any errors either. So I started SQL server profiler to watch the traffic. I saw the if exist drop scripts run for each of the objects but never saw the create scripts run.

**Comment by anupsaund** [comment]
![structure](https://cloud.githubusercontent.com/assets/6728822/8860251/7b558170-317a-11e5-87a4-d760015941ab.PNG)

Tested on;

### Windows Server 2012 - with SQL Server 2014 Standard Edition.

This is a BUG because importing objects into an existing database does not work on SQL Server 2014.
This is equally true if you are wanting to update an object from source control that already exists in the database, or a new object from source control that needs to be created into an existing database.

SQL Server 2008 and 2012 are unaffected.

### Workaround

Drop the database and use the "Import New" option on screen 2.
This will force a create of everything from source control.

**Comment by anupsaund** [comment]
## BUG 1 details

An export was creating a directory structure with a plural object name. i.e. Tables, Views.
Whereas the import was trying to read Table, View as part of the path.

This was causing an import to fail.

## BUG 2 details

The pre-drop of a table during an import was failing due to parentheses which SQL Server could not parse. The parentheses have been removed.

Both fixes are to be included in the next release.
